# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: build-linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup .net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: install and run azurite
        run: npm install -g azurite && mkdir ~/azurite && azurite-blob -l ~/azurite -d ~/azurite\debug.log

      - name: Test it
        run: dotnet run
